### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rid-32** [Re-Boil/domain-data#1]
- [x] Изменить createDomain - принимать набор extenders, возвращать функцию, принимающую имя домена
- [x] Изменить сигнатуру createStore - передавать объект с конфигурацией стора

- [x] Возвращать из createStore объект вида: { store, bindAction, domains }. `domains` будет содержать иерархию доменов с узлами вида { selectors, actions, sagas }

- [x] В createStore биндить экшены

- [x] Реализовать возможность передавать initialState в домен при инициализации

- [x] В Fetch extender добавить в state дату обновления (ISO-8601)

- [x] Убрать из зависимостей redux-thunk и compose-with-devtools. Compose-with-devtools передавать в createStore опционально.

- [x] ${domain}@FETCH подумать над реализацией (.toString())
